apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: r9i4i6hgs-python 
  janus-idp.io/tekton: r9i4i6hgs-python
  backstage.io/kubernetes-id: r9i4i6hgs-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r9i4i6hgs-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml